# Config yaml for Autosklearn run

file: './data/raw/diabetes.csv'
target: 'Age'
task: regression
header: 1
# sep:
# holdout:
# seed:
# output_dir:
# tmp_dir:
time_left_for_this_task: 40
# per_run_time_limit:
# ensemble_size:
# ensemble_nbest: 
# max_models_on_disc: 
# memory_limit: 
# include: 
# exclude: 
# resampling_strategy:
# resampling_strategy_arguments: 
metric: 'mean_squared_error'
scoring_functions: [mean_absolute_error, mean_squared_error]
