# Config yaml for Autosklearn run

file: './data/raw/diabetes.csv'
target: Outcome
task: classification
header: 1
sep: comma
holdout: 0.2
seed: 42
time_left_for_this_task: 40
# per_run_time_limit:
# ensemble_size:
# ensemble_nbest:
# max_models_on_disc:
# memory_limit:
# include:
#   classifier:
#     - random_forest
  # feature_preprocessor:
  #   - no_preprocessing
# exclude:
# resampling_strategy:
# resampling_strategy_arguments:
  # train_size:
  # shuffle:
  # folds:
metric: log_loss
scoring_functions: [roc_auc, log_loss]
