# Config yaml for Autosklearn run

file: 'data/raw/heart.csv'
target: target
task: classification
header: 1
sep: comma
holdout: 0.2
seed: 42
time_left_for_this_task: 40
# per_run_time_limit:
# ensemble_size:
# ensemble_nbest:
# max_models_on_disc:
# memory_limit:
# include:
#   classifier:
#     - random_forest
  # feature_preprocessor:
  #   - no_preprocessing
# exclude:
resampling_strategy: cv
resampling_strategy_arguments:
  train_size: 0.8
  shuffle: True
  folds: 5
metric: log_loss
scoring_functions: [log_loss, roc_auc]
